import type { FeedSourceConfig } from '../types/news.js'

export const AI_FEED_SOURCES: FeedSourceConfig[] = [
  {
    id: 'openai-news',
    name: 'OpenAI News',
    homepageUrl: 'https://openai.com/news/',
    feedUrl: 'https://openai.com/news/rss.xml',
    category: 'official',
    sourceType: 'rss',
    maxItems: 10,
  },
  {
    id: 'huggingface-blog',
    name: 'Hugging Face Blog',
    homepageUrl: 'https://huggingface.co/blog',
    feedUrl: 'https://huggingface.co/blog/feed.xml',
    category: 'official',
    sourceType: 'rss',
    maxItems: 10,
  },
  {
    id: 'mistral-news',
    name: 'Mistral AI News',
    homepageUrl: 'https://mistral.ai/news/',
    feedUrl: 'https://mistral.ai/en/news',
    linkPathNeedle: '/news/',
    category: 'official',
    sourceType: 'html',
    maxItems: 10,
  },
  {
    id: 'anthropic-news',
    name: 'Anthropic Newsroom',
    homepageUrl: 'https://www.anthropic.com/news',
    feedUrl: 'https://www.anthropic.com/news',
    linkPathNeedle: '/news/',
    category: 'official',
    sourceType: 'html',
    maxItems: 10,
  },
  {
    id: 'google-deepmind-news',
    name: 'Google DeepMind News',
    homepageUrl: 'https://deepmind.google/blog/',
    feedUrl: 'https://deepmind.google/blog/',
    linkPathNeedle: '/blog/',
    category: 'official',
    sourceType: 'html',
    maxItems: 10,
  },
  {
    id: 'xai-news',
    name: 'xAI News',
    homepageUrl: 'https://x.ai/news',
    feedUrl: 'https://x.ai/news',
    linkPathNeedle: '/news/',
    category: 'official',
    sourceType: 'html',
    maxItems: 10,
  },
  {
    id: 'cohere-release-notes',
    name: 'Cohere Release Notes',
    homepageUrl: 'https://docs.cohere.com/v2/changelog',
    feedUrl: 'https://docs.cohere.com/v2/changelog',
    category: 'official',
    sourceType: 'html',
    maxItems: 10,
  },
  {
    id: 'meta-llama-news',
    name: 'Meta Llama News',
    homepageUrl: 'https://ai.meta.com/blog/',
    feedUrl: 'https://ai.meta.com/blog/',
    linkPathNeedle: '/blog/',
    includePatterns: ['llama', 'meta ai'],
    category: 'official',
    sourceType: 'html',
    maxItems: 10,
  },
  {
    id: 'qwen-news',
    name: 'Qwen News',
    homepageUrl: 'https://www.alibabacloud.com/blog',
    feedUrl: 'https://www.alibabacloud.com/blog',
    linkPathNeedle: '/blog/',
    includePatterns: ['qwen', 'tongyi', 'qwq'],
    category: 'official',
    sourceType: 'html',
    maxItems: 10,
  },
]
