import type { FeedSourceConfig, SocialSourceConfig } from '../types/news.js'

export const X_ACCOUNT_SOURCES: SocialSourceConfig[] = [
  {
    id: 'x-openai',
    name: 'X / OpenAI',
    accountHandle: 'OpenAI',
    homepageUrl: 'https://x.com/OpenAI',
    category: 'official',
    sourceType: 'html',
    displayName: 'OpenAI',
    company: 'OpenAI',
    modelFamily: 'GPT',
    maxItems: 5,
    latestItems: 1,
    topItems: 2,
    topWindowDays: 7,
  },
  {
    id: 'x-anthropic',
    name: 'X / Anthropic',
    accountHandle: 'AnthropicAI',
    homepageUrl: 'https://x.com/AnthropicAI',
    category: 'official',
    sourceType: 'html',
    displayName: 'Anthropic',
    company: 'Anthropic',
    modelFamily: 'Claude',
    maxItems: 5,
    latestItems: 1,
    topItems: 2,
    topWindowDays: 7,
  },
  {
    id: 'x-deepmind',
    name: 'X / Google DeepMind',
    accountHandle: 'GoogleDeepMind',
    homepageUrl: 'https://x.com/GoogleDeepMind',
    category: 'official',
    sourceType: 'html',
    displayName: 'Google DeepMind',
    company: 'Google DeepMind',
    modelFamily: 'Gemini',
    maxItems: 5,
    latestItems: 1,
    topItems: 2,
    topWindowDays: 7,
  },
  {
    id: 'x-xai',
    name: 'X / xAI',
    accountHandle: 'xai',
    homepageUrl: 'https://x.com/xai',
    category: 'official',
    sourceType: 'html',
    displayName: 'xAI',
    company: 'xAI',
    modelFamily: 'Grok',
    maxItems: 5,
    latestItems: 1,
    topItems: 2,
    topWindowDays: 7,
  },
  {
    id: 'x-mistral',
    name: 'X / Mistral AI',
    accountHandle: 'MistralAI',
    homepageUrl: 'https://x.com/MistralAI',
    category: 'official',
    sourceType: 'html',
    displayName: 'Mistral AI',
    company: 'Mistral AI',
    modelFamily: 'Mistral',
    maxItems: 5,
    latestItems: 1,
    topItems: 2,
    topWindowDays: 7,
  },
  {
    id: 'x-cohere',
    name: 'X / Cohere',
    accountHandle: 'cohere',
    homepageUrl: 'https://x.com/cohere',
    category: 'official',
    sourceType: 'html',
    displayName: 'Cohere',
    company: 'Cohere',
    modelFamily: 'Command',
    maxItems: 5,
    latestItems: 1,
    topItems: 2,
    topWindowDays: 7,
  },
  {
    id: 'x-huggingface',
    name: 'X / Hugging Face',
    accountHandle: 'huggingface',
    homepageUrl: 'https://x.com/huggingface',
    category: 'official',
    sourceType: 'html',
    displayName: 'Hugging Face',
    company: 'Hugging Face',
    maxItems: 5,
    latestItems: 1,
    topItems: 2,
    topWindowDays: 7,
  },
  {
    id: 'x-karpathy',
    name: 'X / Andrej Karpathy',
    accountHandle: 'karpathy',
    homepageUrl: 'https://x.com/karpathy',
    category: 'research',
    sourceType: 'html',
    displayName: 'Andrej Karpathy',
    maxItems: 4,
    latestItems: 1,
    topItems: 2,
    topWindowDays: 7,
  },
  {
    id: 'x-demis-hassabis',
    name: 'X / Demis Hassabis',
    accountHandle: 'demishassabis',
    homepageUrl: 'https://x.com/demishassabis',
    category: 'research',
    sourceType: 'html',
    displayName: 'Demis Hassabis',
    modelFamily: 'Gemini',
    maxItems: 4,
    latestItems: 1,
    topItems: 2,
    topWindowDays: 7,
  },
  {
    id: 'x-ethan-mollick',
    name: 'X / Ethan Mollick',
    accountHandle: 'emollick',
    homepageUrl: 'https://x.com/emollick',
    category: 'media',
    sourceType: 'html',
    displayName: 'Ethan Mollick',
    maxItems: 4,
    latestItems: 1,
    topItems: 2,
    topWindowDays: 7,
  },
  {
    id: 'x-simon-willison',
    name: 'X / Simon Willison',
    accountHandle: 'simonw',
    homepageUrl: 'https://x.com/simonw',
    category: 'media',
    sourceType: 'html',
    displayName: 'Simon Willison',
    maxItems: 4,
    latestItems: 1,
    topItems: 2,
    topWindowDays: 7,
  },
  {
    id: 'x-logan-kilpatrick',
    name: 'X / Logan Kilpatrick',
    accountHandle: 'OfficialLoganK',
    homepageUrl: 'https://x.com/OfficialLoganK',
    category: 'official',
    sourceType: 'html',
    displayName: 'Logan Kilpatrick',
    modelFamily: 'Gemini',
    maxItems: 4,
    latestItems: 1,
    topItems: 2,
    topWindowDays: 7,
  },
  {
    id: 'x-nathan-lambert',
    name: 'X / Nathan Lambert',
    accountHandle: 'natolambert',
    homepageUrl: 'https://x.com/natolambert',
    category: 'research',
    sourceType: 'html',
    displayName: 'Nathan Lambert',
    maxItems: 4,
    latestItems: 1,
    topItems: 2,
    topWindowDays: 7,
  },
]

export function getEnabledXAccountSources(): SocialSourceConfig[] {
  const configuredHandles = process.env.TWITTERAPI_IO_HANDLES
    ?.split(',')
    .map((handle) => handle.trim().replace(/^@/, ''))
    .filter(Boolean)

  if (!configuredHandles?.length) {
    return X_ACCOUNT_SOURCES
  }

  const handleSet = new Set(configuredHandles.map((handle) => handle.toLowerCase()))
  return X_ACCOUNT_SOURCES.filter((source) => handleSet.has(source.accountHandle.toLowerCase()))
}

export function toFeedSourceConfig(source: SocialSourceConfig): FeedSourceConfig {
  return {
    id: source.id,
    name: source.name,
    homepageUrl: source.homepageUrl,
    feedUrl: source.homepageUrl,
    category: source.category,
    sourceType: source.sourceType,
    maxItems: source.maxItems,
  }
}
